### ISSUE TITLE
Word list

### ISSUE THREAD

**Issue by reesericci** [commandblockguy/wordle#6]
The NYT changed the order of the daily words, and now this program is incorrect. This is described in this Reddit post: [https://www.reddit.com/r/wordle/comments/trzu4i/my_wordle_today_is_different_from_everyones/](https://www.reddit.com/r/wordle/comments/trzu4i/my_wordle_today_is_different_from_everyones/)

**Comment by Catakang** [comment]
Riight. So I just spent 3 hours trying to get the current word list and implenting it into a .8xv. I did that very successfully. However, the .8xv file is weird. I put it on the calculator and its still wrong. And for some reason, some words I type that are in the word list I created like brick show up as not in the word list on the calculator. Please fix this. I have given up.

**Comment by reesericci** [comment]
that is some real dedication to Wordle on a calculator my man

**Comment by Catakang** [comment]
I can't figure this out. I made the word list. It can be easily converted to a .8xv. However for some reason, the word list isn't fully registering. Every word list that either is or comes after BLAES is counted as in the list on the calculator. But for some reason, all the words before BLAES aren't counted. I have no idea why. I had no calculator coding experience until yesterday, but even then I still have no idea what I am doing wrong. Here is the new word list in .txt and .8xv form. Note: I couldn't upload the .8xv directly so it's in a zip file.
[WORDS.txt](https://github.com/commandblockguy/wordle/files/8404856/WORDS.txt)
[WORDS.zip](https://github.com/commandblockguy/wordle/files/8404870/WORDS.zip)

**Comment by commandblockguy** [comment]
The word list 8xv is the list of all possible words you can guess in alphabetical order. It uses binary search to find words, so it needs to be in alphabetical order for it to work. Additionally, the list of puzzle solutions is stored in the program itself, not the word list, so I'll need to release an update for it.

**Comment by Catakang** [comment]
Ok cool.
